# test_findvnet_001
run                 = "findvnet"
spice_file          = "tests_data/001.spc"
#top_cell           = "top_cell"
netnames            = "vdd vss vddq vssq"
#
casesensitive       = false
dollar_comment      = false
is_write_1st_spc    = true
is_write_2nd_spc    = true
#log_verbose         = "DEBUG"