from enum import Enum, auto


class Type_tt(Enum):
    INIT = auto()
    #
    NODE_PIN = auto()
    NODE_NODE = auto()
    #
    CELL_R = auto()
    CELL_L = auto()
    CELL_C = auto()
    CELL_K = auto()
    CELL_VS = auto()
    CELL_CS = auto()
    CELL_VCVS = auto()
    CELL_CCVS = auto()
    CELL_VCCS = auto()
    CELL_CCCS = auto()
    CELL_DIODE = auto()
    CELL_MOSFET = auto()
    CELL_BJT = auto()
    CELL_JFET = auto()
    CELL_CELL = auto()
    #
    CELL_NMOS = auto()
    CELL_PMOS = auto()
    CELL_NPN = auto()
    CELL_PNP = auto()
    CELL_NJF = auto()
    CELL_PJF = auto()
    #
    CELL_CELL_DIODE = auto()
    CELL_CELL_NMOS = auto()
    CELL_CELL_PMOS = auto()
    CELL_CELL_NPN = auto()
    CELL_CELL_PNP = auto()
    CELL_CELL_NJF = auto()
    CELL_CELL_PJF = auto()
    #
    INST_R = auto()
    INST_L = auto()
    INST_C = auto()
    INST_K = auto()
    INST_VS = auto()
    INST_CS = auto()
    INST_VCVS = auto()
    INST_CCVS = auto()
    INST_VCCS = auto()
    INST_CCCS = auto()
    INST_DIODE = auto()
    INST_MOSFET = auto()
    INST_BJT = auto()
    INST_JFET = auto()
    INST_INST = auto()
